# Generated by Django 4.1.5 on 2023-01-24 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_alter_company_foundingdate_alter_game_releasedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='foundingdate',
            field=models.DateField(default=None, verbose_name='date founded'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.studio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.company'),
        ),
        migrations.AlterField(
            model_name='game',
            name='releasedate',
            field=models.DateField(default=None, verbose_name='date released'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.game'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='studio',
            name='foundingdate',
            field=models.DateField(default=None, verbose_name='date founded'),
        ),
    ]
