# Generated by Django 4.1.5 on 2023-01-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_company_description_alter_company_foundingdate_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studio',
            new_name='Developer',
        ),
    ]
