# Generated by Django 4.1.5 on 2023-01-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_studio_developer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Developer',
            new_name='Studio',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='developer',
            new_name='Studio',
        ),
    ]
