# Generated by Django 4.1.5 on 2023-01-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_developer_studio_rename_developer_game_studio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studio',
            new_name='Developer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='Studio',
            new_name='developer',
        ),
    ]
