# Generated by Django 4.1.5 on 2023-02-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_image_company_image_developer_image_game_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveSmallIntegerField(default=128),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveSmallIntegerField(default=128),
        ),
    ]
