# Generated by Django 4.1.5 on 2023-02-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_image_height_image_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='image',
            name='binary_blob',
            field=models.BinaryField(editable=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=200),
        ),
    ]
