# Generated by Django 4.1.5 on 2023-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_image_alt_text_alter_image_binary_blob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
