# Generated by Django 4.1.5 on 2023-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_image_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='binary_blob',
            field=models.BinaryField(),
        ),
    ]
