# Generated by Django 4.1.5 on 2023-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_image_filename_alter_image_binary_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='binary_blob',
            field=models.TextField(editable=False),
        ),
    ]
