# Generated by Django 4.1.5 on 2023-02-17 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_image_binary_blob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Publisher',
        ),
    ]
