# Generated by Django 4.1.5 on 2023-03-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_likesusermap_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesusermap',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.game'),
        ),
    ]
