# Generated by Django 4.1.5 on 2023-03-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_userdata_description_alter_userdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
