# Generated by Django 4.1.5 on 2023-06-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='report',
            name='game',
        ),
        migrations.RemoveField(
            model_name='report',
            name='post',
        ),
        migrations.RemoveField(
            model_name='report',
            name='publisher',
        ),
    ]
