# Generated by Django 4.1.5 on 2023-06-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_remove_report_developer_remove_report_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
