# Generated by Django 4.1.5 on 2023-06-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_report_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.DeleteModel(
            name='Warning',
        ),
    ]
