# Generated by Django 4.1.5 on 2023-06-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_post_status_remove_post_type_delete_warning'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['approved', 'count']},
        ),
    ]
