# Generated by Django 4.1.5 on 2023-06-06 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={},
        ),
    ]
